# ASSIGNMENT DAY-3

In [1]:
import numpy as np
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [3]:
import numpy as np
array1=[] 
array2=[]
for each in range(0, 5): 
    element = int(input("list1\n"))
    array1.append(element)
for each in range(0, 5): 
    element = int(input("list2\n"))
    array2.append(element) 
array1 = np.array(array1)
array2 = np.array(array2)
print(np.concatenate((array1,array2)))
print(np.sort(np.concatenate((array1,array2))))

list1
4
list1
5
list1
6
list1
7
list1
8
list2
1
list2
9
list2
2
list2
3
list2
0
[4 5 6 7 8 1 9 2 3 0]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.size)

2
9


In [5]:
import numpy as np
array=np.random.rand(5,)
print(array.ndim)
new_array = array[np.newaxis, :]
print(new_array.ndim)

1
2


In [6]:
import numpy as np
array1=np.random.rand(3,3)
array2=np.random.rand(3,3)
print(np.vstack((array1,array2)))
print() #giving space
print(np.hstack((array1,array2)))

[[0.62400232 0.1578718  0.37992467]
 [0.91881699 0.50309427 0.53365588]
 [0.99814515 0.05405164 0.8765298 ]
 [0.79292627 0.89045442 0.45989605]
 [0.8845482  0.86143926 0.54961475]
 [0.63375572 0.6605045  0.66913851]]

[[0.62400232 0.1578718  0.37992467 0.79292627 0.89045442 0.45989605]
 [0.91881699 0.50309427 0.53365588 0.8845482  0.86143926 0.54961475]
 [0.99814515 0.05405164 0.8765298  0.63375572 0.6605045  0.66913851]]


In [7]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,5,6,3,8,9,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 3, 1, 3, 4, 2, 3, 4], dtype=int64))
